[package]
name = "git-blame-parser"
description = "Parses the git blame porcelain format into a struct."
version = "0.1.1"
edition = "2024"
authors = ["mitsu-ksgr"]
repository = "https://github.com/mitsu-ksgr/git-blame-parser"
license = "MIT"

[dependencies]
